# Generated by Django 5.0.6 on 2024-08-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="temporary_key",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(max_length=50),
        ),
    ]
