# Generated by Django 5.0.6 on 2024-08-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="restaurant_name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="subscription_type",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="authentication.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="license",
            name="computer_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="license",
            name="hardware_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.tenant"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="TemporaryKey",
        ),
    ]
