# Generated by Django 5.0.6 on 2024-08-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="computer_name",
            field=models.CharField(max_length=100),
        ),
    ]
