version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://app_user:app_password@db:5432/app
      REDIS_URL: redis://redis:6379/0
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

  redis:
    image: redis
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Το email για login στο pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin  # Ο κωδικός για το pgAdmin
    ports:
      - "8080:80"  # Προώθηση της θύρας 80 του container στη θύρα 8080 του host
    depends_on:
      - db
    networks:
      - default  # Προσθήκη του pgAdmin στο ίδιο δίκτυο με τη βάση

volumes:
  postgres-data:
