name: Stripe CLI Setup

on: [push]

jobs:
  stripe-cli-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Stripe CLI
      run: wget https://github.com/stripe/stripe-cli/releases/download/v1.21.2/stripe_1.21.2_linux_arm64.deb

    - name: Install Stripe CLI
      run: sudo dpkg -i stripe_1.21.2_linux_arm64.deb

    - name: Authenticate Stripe CLI
      env:
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      run: |
        echo $STRIPE_API_KEY | stripe login --api-key
        stripe whoami

    - name: Forward Stripe webhook events
      run: |
        stripe listen --forward-to localhost:4242/stripe_webhooks
